apiVersion: sinks.knative.dev/v1alpha1
kind: RedisStreamSink
metadata:
  name: mystream
spec:
  address: "redis.redis.svc.cluster.local:6379"
  stream: mystream
  sink:
    ref:
      apiVersion: v1
      kind: Service
      name: event-display
